from collections import OrderedDict


def default_css(images):
    """ Function default_css()

    Generates the OrderedDict that contains the default stylesheet for
    the Tachyonic Web UI.

    Args:
        images (str): URL of path to the images.

    Returns:
       An OrderedDict containing the default css values.
    """
    css = OrderedDict()
    css['.modal-body'] = {}
    css['.modal-body']['overflow-y'] = 'scroll'
    css['.navbar-wrapper'] = {}
    css['.navbar-wrapper']['box-shadow'] = '0 5px 15px rgba(0, 0, 0, .5)'
    css['.modal-header'] = {}
    css['.modal-header']['background-color'] = "#98AFC7"
    css['.modal-header']['border-bottom'] = "1px solid #000"
    css['.red'] = {}
    css['.red']['color'] = 'red'
    css['body'] = {}
    css['body']['background-color'] = '#E7E8EB'
    css['body']['background-image'] = "url(\"%s/bg.jpg\")" % images
    css['body']['background-repeat'] = 'no-repeat'
    css['body']['background-size'] = '100% 100%'
    css['body']['background-attachment'] = 'fixed'
    css['body']['margin-bottom'] = '0px'
    css['body']['margin-left'] = '0px'
    css['body']['margin-right'] = '0px'
    css['body']['margin-top'] = '0px'
    css['.btn-space'] = {}
    css['.btn-space']['margin-left'] = '5px'
    css['.btn-space']['margin-right'] = '5px'
    css['.modal-dialog'] = {}
    css['.modal-dialog']['width'] = '75%'
    css['button.view_button'] = {}
    view_button = css['button.view_button']
    view_button['height'] = '24px'
    view_button['width'] = '24px'
    view_button['border-width'] = '1px'
    view_button['background-color'] = '#FFFFFF'
    view_button['background-image'] = "url(\"%s/view.png\")" % images
    view_button['background-repeat'] = 'no-repeat'
    view_button['border-style'] = 'solid'
    css['button.edit_button'] = {}
    edit_button = css['button.edit_button']
    edit_button['height'] = '24px'
    edit_button['width'] = '24px'
    edit_button['border-width'] = '1px'
    edit_button['background-color'] = '#FFFFFF'
    edit_button['background-image'] = "url(\"%s/edit.png\")" % (images,)
    edit_button['border-style'] = 'solid'
    edit_button['background-repeat'] = 'no-repeat'
    css['.menu-icon'] = {}
    css['.menu-icon']['padding-top'] = '0px'
    css['.menu-icon']['padding-bottom'] = '0px'
    css['.menu-icon']['opacity'] = '0.5'
    css['.menu-icon:hover'] = {}
    css['.menu-icon:hover']['opacity'] = '1'
    css['div.locked'] = {}
    css['div.locked']['display'] = 'none'
    css['div.locked']['background-color'] = '#000000'
    css['div.locked']['overflow'] = 'hidden'
    css['div.locked']['position'] = 'fixed'
    css['div.locked']['z-index'] = '1050'
    css['div.locked']['top'] = '0'
    css['div.locked']['left'] = '0'
    css['div.locked']['height'] = '100%'
    css['div.locked']['width'] = '100%'
    css['div.locked']['opacity'] = '0.4'
    css['div.confirm'] = {}
    css['div.confirm']['display'] = 'none'
    css['div.confirm']['position'] = 'absolute'
    css['div.confirm']['top'] = '100px'
    css['div.confirm']['left'] = '10%'
    css['div.confirm']['right'] = '10%'
    css['div.confirm']['margin'] = 'auto'
    css['div.confirm']['width'] = '600px'
    css['div.confirm']['height'] = 'auto'
    css['div.confirm']['background-color'] = '#FFFFFF'
    css['div.confirm']['z-index'] = '10000'
    css['div.confirm']['overflow'] = 'auto'
    css['div.confirm']['border'] = '1px solid rgba(0, 0, 0, .2)'
    css['div.confirm']['border-radius'] = '6px'
    css['div.confirm']['box-shadow'] = '0 5px 15px rgba(0, 0, 0, .5)'
    css['div.auto-logout'] = {}
    css['div.auto-logout']['display'] = 'none'
    css['div.auto-logout']['position'] = 'absolute'
    css['div.auto-logout']['top'] = '100px'
    css['div.auto-logout']['left'] = '10%'
    css['div.auto-logout']['right'] = '10%'
    css['div.auto-logout']['margin'] = 'auto'
    css['div.auto-logout']['width'] = '500px'
    css['div.auto-logout']['height'] = 'auto'
    css['div.auto-logout']['background-color'] = '#FFFFFF'
    css['div.auto-logout']['z-index'] = '1005'
    css['div.auto-logout']['overflow'] = 'auto'
    css['div.auto-logout']['border'] = '1px solid rgba(0, 0, 0, .2)'
    css['div.auto-logout']['border-radius'] = '6px'
    css['div.auto-logout']['box-shadow'] = '0 5px 15px rgba(0, 0, 0, .5)'
    css['div.window'] = {}
    css['div.window']['opacity'] = '0.9'
    css['div.window']['display'] = 'none'
    css['div.window']['position'] = 'absolute'
    css['div.window']['top'] = '45px'
    css['div.window']['left'] = '10%'
    css['div.window']['right'] = '10%'
    css['div.window']['margin'] = 'auto'
    css['div.window']['width'] = '80%'
    css['div.window']['height'] = 'auto'
    css['div.window']['background-color'] = '#FFFFFF'
    css['div.window']['z-index'] = '1055'
    css['div.window']['overflow'] = 'auto'
    css['div.window']['border'] = '0px solid rgba(0, 0, 0, .2)'
    css['div.window']['border-radius'] = '6px'
    css['div.window']['box-shadow'] = '0 5px 15px rgba(0, 0, 0, .5)'
    css['div.loading'] = {}
    css['div.loading']['display'] = 'none'
    css['div.loading']['overflow'] = 'hidden'
    css['div.loading']['position'] = 'fixed'
    css['div.loading']['z-index'] = '5000'
    css['div.loading']['top'] = '0;'
    css['div.loading']['left'] = '0'
    css['div.loading']['height'] = '100%'
    css['div.loading']['width'] = '100%'
    css['div.loading']['background'] = 'rgba( 255, 255, 255, .6 )'
    css['div.loading']['background'] += "url(\'%s" % (images,)
    css['div.loading']['background'] += '/loader.gif\')'
    css['div.loading']['background'] += '50% 50% no-repeat'

    css['@media (min-width: 1350px)'] = {}
    css['@media (min-width: 1350px)']['.container'] = {}
    css['@media (min-width: 1350px)']['.container']['width'] = '1300px'
    css['@media (max-width: 1000px)'] = {}
    css['@media (max-width: 1000px)']['.navbar-header'] = {}
    css['@media (max-width: 1000px)']['.navbar-header']['float'] = 'none'
    css['@media (max-width: 1000px)']['.navbar-left,.navbar-right'] = {}
    css['@media (max-width: 1000px)']['.navbar-left,.navbar-right']['float'] = 'none !important'
    css['@media (max-width: 1000px)']['.navbar-toggle'] = {}
    css['@media (max-width: 1000px)']['.navbar-toggle']['display'] = 'block'
    css['@media (max-width: 1000px)']['.navbar-collapse'] = {}
    css['@media (max-width: 1000px)']['.navbar-collapse']['border-top'] = '1px solid transparent'
    css['@media (max-width: 1000px)']['.navbar-collapse']['box-shadow'] = 'inset 0 1px 0 rgba(255,255,255,0.1)'
    css['@media (max-width: 1000px)']['.navbar-fixed-top'] = {}
    css['@media (max-width: 1000px)']['.navbar-fixed-top']['top'] = '0'
    css['@media (max-width: 1000px)']['.navbar-fixed-top']['border-width'] = '0 0 1px'
    css['@media (max-width: 1000px)']['.navbar-collapse.collapse'] = {}
    css['@media (max-width: 1000px)']['.navbar-collapse.collapse']['display'] = 'none!important'
    css['@media (max-width: 1000px)']['.navbar-nav'] = {}
    css['@media (max-width: 1000px)']['.navbar-nav']['float'] = 'none!important'
    css['@media (max-width: 1000px)']['.navbar-nav']['margin-top'] = '7.5px'
    css['@media (max-width: 1000px)']['.navbar-nav>li'] = {}
    css['@media (max-width: 1000px)']['.navbar-nav>li']['float'] = 'none'
    css['@media (max-width: 1000px)']['.navbar-nav>li>a'] = {}
    css['@media (max-width: 1000px)']['.navbar-nav>li>a']['padding-top'] = '10px'
    css['@media (max-width: 1000px)']['.navbar-nav>li>a']['padding-bottom'] = '10px'
    css['@media (max-width: 1000px)']['.collapse.in'] = {}
    css['@media (max-width: 1000px)']['.collapse.in']['display'] = 'block !important'
    css['.dropdown-menu'] = {}
    css['.dropdown-menu']['border-radius'] = '0px'
    css['.dropdown-menu']['-webkit-box-shadow'] = 'none'
    css['.dropdown-menu']['box-shadow'] = 'none'
    css['.dropdown-submenu'] = {}
    css['.dropdown-submenu']['position'] = 'initial'
    css['.dropdown-submenu>.dropdown-menu'] = {}
    css['.dropdown-submenu>.dropdown-menu']['top'] = '0'
    css['.dropdown-submenu>.dropdown-menu']['left'] = '100%'
    css['.dropdown-submenu>.dropdown-menu']['margin-top'] = '-1px'
    css['.dropdown-submenu>.dropdown-menu']['margin-left'] = '-1px'
    css['.dropdown-submenu>.dropdown-menu']['-webkit-border-radius'] = '0'
    css['.dropdown-submenu>.dropdown-menu']['-moz-border-radius'] = '0'
    css['.dropdown-submenu>.dropdown-menu']['border-radius'] = '0'
    css['.dropdown-submenu>.dropdown-menu']['min-height'] = '101%'
    css['.dropdown-submenu:hover>.dropdown-menu'] = {}
    css['.dropdown-submenu:hover>.dropdown-menu']['display'] = 'block'
    css['.dropdown-submenu>a:after'] = {}
    css['.dropdown-submenu>a:after']['display'] = 'block'
    css['.dropdown-submenu>a:after']['content'] = '" "'
    css['.dropdown-submenu>a:after']['float'] = 'right'
    css['.dropdown-submenu>a:after']['width'] = '0'
    css['.dropdown-submenu>a:after']['height'] = '0'
    css['.dropdown-submenu>a:after']['border-color'] = 'transparent'
    css['.dropdown-submenu>a:after']['border-style'] = 'solid'
    css['.dropdown-submenu>a:after']['border-width'] = '5px 0 5px 5px'
    css['.dropdown-submenu>a:after']['border-left-color'] = '#ccc'
    css['.dropdown-submenu>a:after']['margin-top'] = '5px'
    css['.dropdown-submenu>a:after']['margin-right'] = '-10px'
    css['.dropdown-submenu:hover>a:after'] = {}
    css['.dropdown-submenu:hover>a:after']['border-left-color'] = '#fff'
    css['.dropdown-submenu.pull-left'] = {}
    css['.dropdown-submenu.pull-left']['float'] = 'none'
    css['.dropdown-submenu.pull-left>.dropdown-menu'] = {}
    css['.dropdown-submenu.pull-left>.dropdown-menu']['left'] = '-100%'
    css['.dropdown-submenu.pull-left>.dropdown-menu']['margin-left'] = '10px'
    css['.dropdown-submenu.pull-left>.dropdown-menu']['-webkit-border-radius'] = '6px 0 6px 6px'
    css['.dropdown-submenu.pull-left>.dropdown-menu']['-moz-border-radius'] = '6px 0 6px 6px'
    css['.dropdown-submenu.pull-left>.dropdown-menu']['border-radius'] = '6px 0 6px 6px'
    css['#popup'] = {}
    css['#popup']['z-index'] = '4000'
    css['#popup']['width'] = '300px'
    css['#popup']['position'] = 'fixed'
    css['#popup']['top'] = '50px'
    css['#popup']['left'] = 'auto'
    css['#popup']['right'] = '10px'
    css['#popup']['font-family'] = 'helvetica,arial,sans-serif'
    css['#popup']['font-size'] = '8pt'
    css['div.error'] = {}
    css['div.error']['background-color'] = '#f4e2e3'
    css['div.error']['color'] = '#9a6e6f'
    css['div.error']['display'] = 'none'
    css['div.warning'] = {}
    css['div.warning']['background-color'] = '#fff4c3'
    css['div.warning']['color'] = '#b09100'
    css['div.warning']['display'] = 'none'
    css['div.info'] = {}
    css['div.info']['background-color'] = '#deeff7'
    css['div.info']['color'] = '#6d8a98'
    css['div.info']['display'] = 'none'
    css['div.ids'] = {}
    css['div.ids']['color'] = '#006621'
    css['div.search_result'] = {}
    css['div.search_result']['padding-bottom'] = '10px'
    css['div.search_title'] = {}
    css['div.search_title']['color'] = ''
    css['div.search_title']['font-size'] = '18px'
    css['div.success'] = {}
    css['div.success']['background-color'] = '#e2f2dd'
    css['div.success']['color'] = '#598766'
    css['div.success']['display'] = 'none'
    css['div.popup'] = {}
    css['div.popup']['border-color'] = '#D8D8D8'
    css['div.popup']['border-style'] = 'solid'
    css['div.popup']['border-width'] = '1px'
    css['div.popup']['margin-bottom'] = '10px'
    css['div.popup']['margin-left'] = '0px'
    css['div.popup']['margin-right'] = '0px'
    css['div.popup']['margin-top'] = '0px'
    css['div.popup']['padding-bottom'] = '5px'
    css['div.popup']['padding-left'] = '5px'
    css['div.popup']['padding-right'] = '5px'
    css['div.popup']['padding-top'] = '5px'
    css['div.popup']['width'] = '100%'
    css['div.popup']['border-radius'] = '8px'
    css['div.popup']['overflow'] = 'hidden'
    css['div.signin'] = {}
    css['div.signin']['width'] = '50%'
    css['div.signin']['max-width'] = '400px'
    css['div.signin']['min-width'] = '200px'
    css['div.signin']['margin'] = 'auto'
    css['div.box'] = {}
    css['div.box']['width'] = 'auto'
    css['div.box']['border-style'] = 'solid'
    css['div.box']['padding-top'] = '2px'
    css['div.box']['padding-bottom'] = '2px'
    css['div.box']['padding-left'] = '2px'
    css['div.box']['padding-right'] = '2px'
    css['div.box']['border-color'] = '#e3e3e3'
    css['div.box']['background-color'] = '#f5f5f5'
    css['div.box']['border-width'] = '1px'
    css['div.box']['box-shadow'] = 'inset 0 1px 1px rgba(0,0,0,.05)'
    css['div.box']['border-radius'] = '3px'
    css['div.box']['margin-bottom'] = '5px'
    css['div.box']['font-family'] = 'helvetica,arial,sans-serif'
    css['div.box']['font-size'] = '12px'
    css['div.box']['min-height'] = '12px'
    css['div.block'] = {}
    css['div.block']['box-shadow'] = '5px 5px 5px #888888'
    css['div.block']['opacity'] = '0.8'
    css['div.block']['background-color'] = '#FFFFFF'
    css['div.block']['border-color'] = '#D8D8D8'
    css['div.block']['border-style'] = 'solid'
    css['div.block']['border-width'] = '1px'
    css['div.block']['color'] = '#5B5B5B'
    css['div.block']['font-family'] = 'helvetica,arial,sans-serif'
    css['div.block']['font-size'] = '12px'
    css['div.block']['margin-bottom'] = '10px'
    css['div.block']['margin-left'] = '0px'
    css['div.block']['margin-right'] = '0px'
    css['div.block']['margin-top'] = '0px'
    css['div.block']['padding-bottom'] = '5px'
    css['div.block']['padding-left'] = '5px'
    css['div.block']['padding-right'] = '5px'
    css['div.block']['padding-top'] = '5px'
    css['div.block']['width'] = '100%'
    css['div.block']['border-radius'] = '8px'
    css['span.title'] = {}
    css['span.title']['font-family'] = 'helvetica,arial,sans-serif'
    css['span.title']['font-weight'] = 'bold'
    css['div.block']['font-size'] = '12px'
    css['div.block_title'] = {}
    css['div.block_title']['border-bottom-width'] = '1px'
    css['div.block_title']['border-color'] = '#D8D8D8'
    css['div.block_title']['border-left-width'] = '0px'
    css['div.block_title']['border-right-width'] = '0px'
    css['div.block_title']['border-style'] = 'solid'
    css['div.block_title']['border-top-width'] = '0px'
    css['div.block_title']['color'] = '#318BBB'
    css['div.block_title']['font'] = "bold 15px 'lucida sans',"
    css['div.block_title']['font'] += "'trebuchet MS', 'Tahoma'"
    css['div.block_title']['margin-bottom'] = '5px'
    css['div.block_title']['margin-left'] = '0px'
    css['div.block_title']['margin-right'] = '0px'
    css['div.block_title']['margin-top'] = '0px'
    css['div.block_title']['width'] = '100%'
    css['div.block_content'] = {}
    css['div.block_content']['border-bottom-width'] = '0px'
    css['div.block_content']['border-left-width'] = '0px'
    css['div.block_content']['border-right-width'] = '0px'
    css['div.block_content']['border-top-width'] = '0px'
    css['div.block_content']['margin-bottom'] = '5px'
    css['div.block_content']['margin-left'] = '0px'
    css['div.block_content']['margin-right'] = '0px'
    css['div.block_content']['margin-top'] = '0px'
    css['div.block_content']['width'] = '100%'
    css['div.block_content']['overflow'] = 'hidden'
    css['div.block_menu'] = {}
    css['div.block_menu']['border-bottom-width'] = '0px'
    css['div.block_menu']['border-left-width'] = '0px'
    css['div.block_menu']['border-right-width'] = '0px'
    css['div.block_menu']['border-top-width'] = '0px'
    css['div.block_menu']['margin-bottom'] = '5px'
    css['div.block_menu']['margin-left'] = '0px'
    css['div.block_menu']['margin-right'] = '0px'
    css['div.block_menu']['margin-top'] = '0px'
    css['div.block_menu']['width'] = '100%'
    css['div.block_menu']['overflow'] = 'visible'
    css['div.menu'] = {}
    css['div.menu']['z-index'] = '1003'
    css['div.menu']['position'] = 'relative'
    css['div.menu_accounts'] = {}
    css['div.menu_accounts']['z-index'] = '1001'
    css['div.menu_accounts']['position'] = 'relative'
    css['div.menu_services'] = {}
    css['div.menu_services']['z-index'] = '1000'
    css['div.menu_services']['position'] = 'relative'
    css['div.push_top_searchbox'] = {}
    css['div.push_top_searchbox']['height'] = '40px'
    css['div.push_top_searchbox']['width'] = '100%'
    css['div.push_top_searchbox']['clear'] = 'both'
    css['div.push_top'] = {}
    css['div.push_top']['height'] = '70px'
    css['div.push_top']['width'] = '100%'
    css['div.push_top']['clear'] = 'both'
    css['div.push_top']['z-index'] = '1'
    css['div.push_bottom'] = {}
    css['div.push_bottom']['height'] = '25px'
    css['div.push_bottom']['width'] = '100%'
    css['div.push_bottom']['clear'] = 'both'
    css['div.push_bottom']['z-index'] = '1'
    css['.top-bar'] = {}
    css['.top-bar']['top'] = '50px'
    css['.top-bar']['padding-top'] = '50px'
    css['.top-bar']['padding-bottom'] = '5px'
    css['.top-bar']['margin-top'] = '0px'
    css['.top-bar']['margin-bottom'] = '5px'
    css['.top-bar']['width'] = '100%'
    css['.top-bar']['z-index'] = '1029'
    css['.tenant-bar-box'] = {}
    css['.tenant-bar-box']['padding-top'] = '8px'
    css['.tenant-bar-box']['padding-left'] = '8px'
    css['.tenant-bar-box']['padding-right'] = '8px'
    css['.tenant-bar-box']['padding-bottom'] = '8px'
    css['.tenant-bar-box']['border'] = '0px solid rgba(0, 0, 0, .2)'
    css['.tenant-bar-box']['border-radius'] = '0px 0px 6px 6px'
    css['.tenant-bar-box']['box-shadow'] = '0 5px 15px rgba(0, 0, 0, .5)'
    css['.search-bar-box'] = {}
    css['.search-bar-box']['padding-top'] = '8px'
    css['.search-bar-box']['padding-left'] = '8px'
    css['.search-bar-box']['padding-right'] = '8px'
    css['.search-bar-box']['padding-bottom'] = '8px'
    css['.search-bar-box']['border'] = '0px solid rgba(0, 0, 0, .2)'
    css['.search-bar-box']['border-radius'] = '0px 0px 6px 6px'
    css['.search-bar-box']['box-shadow'] = '0 5px 15px rgba(0, 0, 0, .5)'
    css['footer'] = {}
    css['footer']['background-color'] = '#5B5B5B'
    css['footer']['bottom'] = '0px'
    css['footer']['clear'] = 'both'
    css['footer']['color'] = '#FFFFFF'
    css['footer']['font-size'] = '12px'
    css['footer']['height'] = '20px'
    css['footer']['line-height'] = '20px'
    css['footer']['margin-bottom'] = '0px'
    css['footer']['margin-top'] = '0px'
    css['footer']['position'] = 'fixed'
    css['footer']['text-align'] = 'center'
    css['footer']['z-index'] = '1010'
    css['footer']['width'] = '100%'
    css['footer:before'] = {}
    css['footer:before'][
        'content'] = "\"Tachyonic Framework - Copyright (c) 2016 to 2017, Christiaan Frans Rademan, Allan Swanepoel, Dave Kruger. All rights resevered. BSD3-Clause License\""
    css['footer:after'] = {}
    css['.search-bar-box']['min-width'] = '40%'
    css['.tenant-bar-box']['min-width'] = '50%'

    return css
